# Generated by Django 2.0.6 on 2018-10-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20181018_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
